name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch dev.to articles
      run: |
        articles=$(curl -s https://dev.to/api/articles?username=samuel-braun)
        echo "ARTICLES=${articles}" >> $GITHUB_ENV

    - name: Update README
      run: |
        python .github/scripts/update_readme.py

    - name: Commit and push
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add README.md
        git commit -m "Updated README with latest dev.to articles"
        git push
